
data:
  url: https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv
  target: species

split:
  test_size: 0.2
  seed: 42

model:
  n_estimators: 200
  max_depth: null
  min_samples_split: 2
  random_state: 42
