name: CI - DVC Repro & MLflow Log

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # OPTIONAL: kalau mau tetap ada guard, tapi jangan paksa init
      - name: Ensure DVC exists (skip if already initialized)
        run: |
          if [ ! -d ".dvc" ]; then
            dvc init -q
          fi

      # OPTIONAL: kalau kamu BELUM menambah os.makedirs di evaluate.py,
      # tetap bikin folder output agar eval tidak gagal.
      - name: Prepare output dirs
        run: mkdir -p reports

      - name: Reproduce pipeline
        run: dvc repro -v

      - name: Show metrics
        run: cat reports/metrics.json

      - name: Upload artifacts (metrics, model, mlruns)
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            reports/metrics.json
            models/model.joblib
            mlruns
          if-no-files-found: ignore
